/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calc;

public class Calc {
    public static void main(String[] args) {}

    public Integer add(int integer1, int integer2) {
        return integer1 + integer2;
    }
}
