/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wordgame;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        Game game = new Game(new WordGenerator());
        System.out.println(game.getWordToGuess());
        Character guess = (in.nextLine()).charAt(0);
        System.out.println(game.guessLetter(guess));
        in.close();
    }
}
