/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calc;

import org.junit.Test;
import static org.junit.Assert.*;

public class CalcTest {
    @Test public void testAddsTwoAndTwo() {
        Calc calc = new Calc();
        assertEquals("2 + 2 should equal 4", Integer.valueOf(4), calc.add(2, 2));
    }
}
